# Generated by Django on 2026-08-27
import django.core.validators
import django.db.models.deletion
import marketplace.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('professional_title', models.CharField(blank=True, help_text='e.g. Full-Stack Developer | Python & AI Specialist', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills (e.g., Python, Django, React, PostgreSQL)', null=True)),
                ('experience', models.TextField(blank=True, help_text='Years of experience or background summary', null=True)),
                ('bio', models.TextField(blank=True, help_text='Detailed summary of professional strengths and services', null=True)),
                ('portfolio_website', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=marketplace.models.freelancer_avatar_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('scam', 'Client Scam'), ('non_payment', 'Non-Payment / Milestone Issue'), ('misleading_project', 'Misleading Project / Scope Creep'), ('abuse', 'Abuse / Harassment'), ('suspicious_activity', 'Suspicious Activity'), ('other', 'Other Issue')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to='marketplace.freelancerprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_reports', to='marketplace.marketplaceproject')),
                ('reported_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='marketplace.clientprofile')),
            ],
            options={
                'verbose_name': 'Freelancer Report',
                'verbose_name_plural': 'Freelancer Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
