# Generated by Django 6.0.7 on 2026-08-27 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_freelancerprofile_freelancerreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='MarketplaceDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('payment', 'Payment & Milestones'), ('delivery', 'Non-Performance & Delivery Failure'), ('quality', 'Scope & Quality Discrepancy'), ('communication', 'Unresponsive / Abandonment'), ('terms_breach', 'Terms & Policy Breach'), ('scam', 'Suspected Fraud / Scam'), ('other', 'Other Dispute')], default='delivery', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, help_text='Links, logs, or detailed evidence statements', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=30)),
                ('resolution_type', models.CharField(choices=[('pending', 'Pending Resolution'), ('favor_client', 'Resolved in Favor of Client (Refund Recommended)'), ('favor_freelancer', 'Resolved in Favor of Freelancer (Payment Release)'), ('mutual_settlement', 'Mutual Settlement / Partial Split'), ('dismissed', 'Dismissed / No Action Required')], default='pending', max_length=30)),
                ('resolution', models.TextField(blank=True, help_text='Final verdict and resolution rationale', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Confidential administrative notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='marketplace.clientprofile')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='marketplace.freelancerprofile')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='marketplace.marketplaceproject')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_marketplace_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace Dispute',
                'verbose_name_plural': 'Marketplace Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('other', 'Other / General User')], default='client', max_length=20)),
                ('category', models.CharField(choices=[('account_problem', 'Account & Authentication Problem'), ('project_problem', 'Project & Workspace Issue'), ('payment_problem', 'Payment & Milestone Issue'), ('scam_report', 'Scam / Security Alert'), ('technical_issue', 'Technical Issue / Bug'), ('other', 'Other Support Request')], default='other', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Support Ticket',
                'verbose_name_plural': 'Platform Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
