# Generated by Django 6.0.7 on 2026-08-27 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_freelancerreport_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('identity_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('identity_type', models.CharField(blank=True, help_text='e.g. Aadhaar / National ID, Passport, Voter ID, Driver License', max_length=100, null=True)),
                ('identity_holder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('identity_reference_id', models.CharField(blank=True, help_text='Secure simulation/reference token (no raw IDs stored publicly)', max_length=100, null=True)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pan_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('pan_masked', models.CharField(blank=True, help_text='Masked PAN e.g. XXXXXX1234 (never full PAN publicly)', max_length=20, null=True)),
                ('pan_verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('payment_account_type', models.CharField(blank=True, help_text='e.g. Razorpay Route Verified, UPI KYC Linked, Bank Account Verified', max_length=100, null=True)),
                ('payment_account_reference', models.CharField(blank=True, help_text='Safe masked reference token', max_length=100, null=True)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completion_percentage', models.IntegerField(default=0)),
                ('profile_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=20)),
                ('admin_review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('admin_review_notes', models.TextField(blank=True, null=True)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('final_verification_status', models.CharField(choices=[('not_verified', 'Not Verified'), ('pending_admin_review', 'Pending Admin Review'), ('verified', 'Verified Freelancer'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='not_verified', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_freelancer_verifications', to=settings.AUTH_USER_MODEL)),
                ('freelancer_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='marketplace.freelancerprofile')),
            ],
            options={
                'verbose_name': 'Freelancer Verification',
                'verbose_name_plural': 'Freelancer Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
