# Generated by Django 6.0.7 on 2026-08-05 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('microsoft', 'Microsoft'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('apple', 'Apple'), ('discord', 'Discord'), ('slack', 'Slack'), ('reddit', 'Reddit'), ('gitlab', 'GitLab')], max_length=30)),
                ('code_verifier', models.CharField(blank=True, max_length=128, null=True)),
                ('next_url', models.CharField(default='/dashboard/', max_length=512)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OAuth State Token',
                'verbose_name_plural': 'OAuth State Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthLoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('microsoft', 'Microsoft'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('apple', 'Apple'), ('discord', 'Discord'), ('slack', 'Slack'), ('reddit', 'Reddit'), ('gitlab', 'GitLab')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled (user denied)'), ('error', 'Provider Error')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_new_account', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Login History',
                'verbose_name_plural': 'OAuth Login History Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('microsoft', 'Microsoft'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('apple', 'Apple'), ('discord', 'Discord'), ('slack', 'Slack'), ('reddit', 'Reddit'), ('gitlab', 'GitLab')], max_length=30)),
                ('provider_user_id', models.CharField(help_text='Unique user identifier returned by the OAuth provider', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_photo_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='True if provider confirmed this email as verified')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
